### ISSUE TITLE
There is no leader in mysql cluster

### ISSUE THREAD

**Issue by swimmingCreative** [FudanSELab/train-ticket#234]
### Summary
Run command: "helm install nacosdb --set mysql.mysqlUser=nacos --set mysql.mysqlPassword=Abcd1234# --set mysql.mysqlDatabase=nacos deployment/kubernetes-manifests/quickstart-k8s/charts/mysql -n tt", there is no leader in mysql cluster.

### Expected behaviour

There should be one leader pod and 2 follower pod in mysql cluster. The leader pod should be with label "role=leader", and the mysql "read-only" should be 0.

### Current behaviour

All of them are with label: "role=follower", and "read-only" = 1.

### Steps to reproduce 

cd ./train_ticket
helm install nacosdb --set mysql.mysqlUser=nacos --set mysql.mysqlPassword=Abcd1234

### Your environment

OS(e.g: `cat /etc/os-release`):

docker version(e.g `docker version`): 

 
docker-compose version (e.g `docker-compose --version`):

 
Kubernetes version(use `kubectl version`):

istio version:

**Comment by swimmingCreative** [comment]
Manual set the leader and mysql 'read-only'. This problem is solved.

**Comment by saibhargav97v** [comment]
How to manually set the leader and mysql 'read-only' ?

**Comment by saibhargav97v** [comment]
Hi @swimmingCreative, I was able to set 1 leader and 2 followers but the issue remains the same. How to set mysql 'read-only' ?
